mysql -u root -p test
create database test;
show databases;
show tables;
use test;
desc test;
show columns from test;
show columns from information_schema.columns;
select * from information_schema.columns where table_name='test';
select count(*) from information_schema.columns where table_name='I_ITM_STOREITEM';
select column_name, data_type from information_schema.columns where table_name='test';
show variables like '%char%';
set names gbk;
set names utf8;
set character_set_server = gbk;
set character_set_server = utf8;
show create database test;
alter database test character set gbk;
alter database test character set utf8;
show create table I_ITM_STOREITEM;
alter table I_ITM_STOREITEM character set gbk;
alter table I_ITM_STOREITEM character set utf8;
show variables like '%error';