
CREATE TABLESPACE ADJINFO_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ADJINFO_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ADJINFO_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ADJINFO_2.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ADJINFO_WD DATAFILE 
  'F:\Software\Oracle\Tablespaces\ADJINFO_WD.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE BACK_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\BACK_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE BALANCE_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\BALANCE_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_0.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_2.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_3.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_4 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_4.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_5 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_5.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_6 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_6.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_7 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_7.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_8 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_8.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESALES_9 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ESALES_9.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE EXJH_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\EXJH_1.DAT' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE FINANCE_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\FINANCE_1.DAT' SIZE 70M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HISTORY_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HISTORY_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE HPC_QUERY_0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_0.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_10 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_10.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_2.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_3.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_4 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_4.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_5 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_5.DAT' SIZE 300M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_6 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_6.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_7 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_7.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_8 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_8.DAT' SIZE 45M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_9 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_9.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HPC_QUERY_IDX DATAFILE 
  'F:\Software\Oracle\Tablespaces\HPC_QUERY_IDX.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_0.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_2.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_3.DAT' SIZE 90M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_4 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_4.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_5 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_5.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_6 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_6.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_7 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_7.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_8 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_8.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HSLSALES_9 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HSLSALES_9.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_EHPC DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_EHPC.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_EHSL DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_EHSL.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_FIN DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_FIN.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_HBL DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_HBL.DAT' SIZE 65M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_HCT DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_HCT.DAT' SIZE 45M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_HJST DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_HJST.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_HPC DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_HPC.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED,
  'F:\Software\Oracle\Tablespaces\IDX_HPC1.DAT' SIZE 1000M AUTOEXTEND ON NEXT 5M MAXSIZE 4096M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_HSL DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_HSL.DAT' SIZE 1000M AUTOEXTEND ON NEXT 10M MAXSIZE 4096M,
  'F:\Software\Oracle\Tablespaces\IDX_HSL1.DAT' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_HST DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_HST.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_HSY DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_HSY.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_ITM DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_ITM.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_OTH DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_OTH.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_VIP DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_VIP.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_VIP_Q DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_VIP_Q.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_VIP1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_VIP1.DAT' SIZE 60M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_WKFL DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_WKFL.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE INV_IDX DATAFILE 
  'F:\Software\Oracle\Tablespaces\INV_IDX.DAT' SIZE 55M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE INVOICE DATAFILE 
  'F:\Software\Oracle\Tablespaces\INVOICE.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ITEM_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ITEM_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ITEM_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ITEM_2.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE MASTER DATAFILE 
  'F:\Software\Oracle\Tablespaces\MASTER.DAT' SIZE 1000M AUTOEXTEND ON NEXT 10M MAXSIZE 4096M,
  'F:\Software\Oracle\Tablespaces\MASTER0_2.DAT' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  'F:\Software\Oracle\Tablespaces\MASTER0_1.DAT' SIZE 1000M AUTOEXTEND ON NEXT 10M MAXSIZE 4096M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE MASTER_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\MASTER_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  'F:\Software\Oracle\Tablespaces\MASTER1_1.DAT' SIZE 1000M AUTOEXTEND ON NEXT 10M MAXSIZE 4096M,
  'F:\Software\Oracle\Tablespaces\MASTER1_2.DAT' SIZE 1000M AUTOEXTEND ON NEXT 10M MAXSIZE 6144M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ORDER_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\ORDER_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE PURCHASE_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\PURCHASE_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_1.DAT' SIZE 1000M AUTOEXTEND ON NEXT 5M MAXSIZE 4096M,
  'F:\Software\Oracle\Tablespaces\SALES_1_01.DAT' SIZE 1000M AUTOEXTEND ON NEXT 5M MAXSIZE 6144M,
  'F:\Software\Oracle\Tablespaces\SALES_1_02.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_2.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_3.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_01 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_01.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_02 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_02.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_03 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_03.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_04 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_04.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_05 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_05.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_06 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_06.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_07 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_07.DAT' SIZE 90M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SALES_4_08 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_08.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_09 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_09.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_10 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_10.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_11 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_11.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_12 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_12.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_13 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_13.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_14 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_14.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_4_15 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_4_15.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_5 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_5.DAT' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_6 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_6.DAT' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SALES_HIS DATAFILE 
  'F:\Software\Oracle\Tablespaces\SALES_HIS.DAT' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SCHEDULE DATAFILE 
  'F:\Software\Oracle\Tablespaces\SCHEDULE.DAT' SIZE 20M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SCHEDULE_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\SCHEDULE_1.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STOCK_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\STOCK_1.DAT' SIZE 1000M AUTOEXTEND ON NEXT 5M MAXSIZE 4G,
  'F:\Software\Oracle\Tablespaces\STOCK_1_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STOCK_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\STOCK_2.DAT' SIZE 170M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_1.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_2.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_3.DAT' SIZE 100M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE00.DAT' SIZE 90M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE01.DAT' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX_PARK DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_PARK.dbf' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE  UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

CREATE TABLESPACE PARK DATAFILE 
  'F:\Software\Oracle\Tablespaces\PARK.dbf' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE  UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE02.DAT' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE03.DAT' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE4 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE04.DAT' SIZE 20M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE5 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE05.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE6 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE06.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE7 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE07.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE8 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE08.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_BALANCE9 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_BALANCE09.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY0.DAT' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY1.DAT' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY2.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY3.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY4 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY4.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY5 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY5.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY6 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY6.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY7 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY7.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY8 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY8.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE VIP_QUERY9 DATAFILE 
  'F:\Software\Oracle\Tablespaces\VIP_QUERY9.DAT' SIZE 20M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE WKFL_0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\WKFL_0.DAT' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE WKFL_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\WKFL_1.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HJST_QUERY_0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HJST_QUERY_0.DAT' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE   UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE HJST_QUERY_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\HJST_QUERY_1.DAT' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE   UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CS_GONGZI DATAFILE 
  'F:\Software\Oracle\Tablespaces\CS_GONGZI.DAT' SIZE 310M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE CS_INDEX DATAFILE 
  'F:\Software\Oracle\Tablespaces\CS_INDEX.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE CSST_QUERY_0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\CSST_QUERY_0.dat' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 1024M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE CSST_QUERY_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\CSST_QUERY_1.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE HJ_GONGZI DATAFILE 
  'F:\Software\Oracle\Tablespaces\HJ_GONGZI.DAT' SIZE 310M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE HJ_INDEX DATAFILE 
  'F:\Software\Oracle\Tablespaces\HJ_INDEX.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE IDX_CSST DATAFILE 
  'F:\Software\Oracle\Tablespaces\IDX_CSST.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE IDX_MEC DATAFILE 
  'F:\Software\Oracle\Tablespaces\idx_mec.dat' SIZE 1470M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE LB_GONGZI DATAFILE 
  'F:\Software\Oracle\Tablespaces\LB_GONGZI.DAT' SIZE 310M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE LB_INDEX DATAFILE 
  'F:\Software\Oracle\Tablespaces\LB_INDEX.DAT' SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;




CREATE TABLESPACE MECSALES_0 DATAFILE 
  'F:\Software\Oracle\Tablespaces\mecsales_0.dat' SIZE 140M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE MECSALES_1 DATAFILE 
  'F:\Software\Oracle\Tablespaces\mecsales_1.dat' SIZE 140M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE MECSALES_2 DATAFILE 
  'F:\Software\Oracle\Tablespaces\mecsales_2.dat' SIZE 140M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE MECSALES_3 DATAFILE 
  'F:\Software\Oracle\Tablespaces\mecsales_3.dat' SIZE 140M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE MECSALES_4 DATAFILE 
  'F:\Software\Oracle\Tablespaces\mecsales_4.dat' SIZE 140M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE MECSALES_5 DATAFILE 
  'F:\Software\Oracle\Tablespaces\mecsales_5.dat' SIZE 140M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE MECSALES_6 DATAFILE 
  'F:\Software\Oracle\Tablespaces\mecsales_6.dat' SIZE 140M AUTOEXTEND ON NEXT 10M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
