-- CREATE USER "C##Scott" IDENTIFIED BY '123456';
-- GRANT CONNECT, RESOURCE TO "C##SCOTT";
-- GRANT UNLIMITED TABLESPACE TO "C##SCOTT"
-- DROP USER C##Scott CASCADE;
DROP USER C##DEP6 CASCADE;
CREATE USER C##DEP6
  IDENTIFIED BY 123456
  DEFAULT TABLESPACE MASTER_1
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 5 Roles for C##DEP6 
  GRANT CONNECT TO C##DEP6;
  GRANT DBA TO C##DEP6;
  GRANT EXP_FULL_DATABASE TO C##DEP6;
  GRANT IMP_FULL_DATABASE TO C##DEP6;
  GRANT RESOURCE TO C##DEP6;
  ALTER USER C##DEP6 DEFAULT ROLE ALL;
  -- 8 System Privileges for C##DEP6 
  GRANT CREATE ANY DIRECTORY TO C##DEP6;
  GRANT CREATE ANY TRIGGER TO C##DEP6;
  GRANT CREATE SESSION TO C##DEP6;
  GRANT CREATE VIEW TO C##DEP6;
  GRANT DEBUG ANY PROCEDURE TO C##DEP6;
  GRANT DEBUG CONNECT SESSION TO C##DEP6;
  GRANT SELECT ANY TABLE TO C##DEP6;
  GRANT UNLIMITED TABLESPACE TO C##DEP6;